SELECT c.NAME, COUNT(*) AS PROJECT_COUNT
FROM client c
JOIN project p ON c.ID = p.CLIENT_ID
GROUP BY c.ID, c.NAME
HAVING COUNT(*) = (
  SELECT COUNT(*)
  FROM project
  GROUP BY CLIENT_ID
  ORDER BY COUNT(*) DESC
  LIMIT 1
);